id: P3450CB8A
initial_creation_type: ocr
source_metadata:
  volumes:
    0a7ff48b5bd04ca28174fd8ecae09825:
      base_file: v062.txt
      image_group_id: I1PD96845
      title: འཕགས་པ་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 856
      volume_number: 62
